{
  'targets': [
    {
      'target_name': 'wrapper-native',
      'sources': [ 'src/wrapper.cc' ],
      'include_dirs': ["<!@(node -p \"require('node-addon-api').include\")", "/root/ns-allinone-3.29/bake/build", "/root/ns-allinone-3.29/bake/build/include/ns3-dev"],
      'dependencies': ["<!(node -p \"require('node-addon-api').gyp\")"],
      'cflags!': [ '-fno-exceptions' ],
      'cflags_cc!': [ '-fno-exceptions', '-fno-rtti' ],
      'cflags_cc': [ '--std=c++17', '-lstdc++fs', '-I/root/ns-allinone-3.29/bake/build/include' ],
      'xcode_settings': {
        'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
        'CLANG_CXX_LIBRARY': 'libc++',
        'MACOSX_DEPLOYMENT_TARGET': '10.7'
      },
      'msvs_settings': {
        'VCCLCompilerTool': { 'ExceptionHandling': 1 },
      }, 
  'libraries': [
    "-lstdc++fs",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-antenna-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-aodv-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-applications-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-bridge-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-buildings-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-config-store-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-core-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-csma-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-csma-layout-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-dsdv-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-dsr-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-energy-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-fd-net-device-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-flow-monitor-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-internet-apps-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-internet-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-lr-wpan-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-lte-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-mesh-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-mobility-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-mpi-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-netanim-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-network-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-nix-vector-routing-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-olsr-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-point-to-point-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-point-to-point-layout-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-propagation-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-sixlowpan-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-spectrum-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-stats-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-tap-bridge-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-test-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-topology-read-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-traffic-control-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-uan-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-virtual-net-device-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-wave-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-wifi-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-wimax-debug.so",
    "/root/ns-allinone-3.29/bake/build/lib/libns3-dev-openflow-debug.so",
  ], 
    }
  ], 
}
