const systemsSupported = ['linux-x64'];

const sharedObjects = [
  'libns3-dev-antenna-debug.so',
  'libns3-dev-aodv-debug.so',
  'libns3-dev-applications-debug.so',
  'libns3-dev-bridge-debug.so',
  'libns3-dev-buildings-debug.so',
  'libns3-dev-config-store-debug.so',
  'libns3-dev-core-debug.so',
  'libns3-dev-csma-debug.so',
  'libns3-dev-csma-layout-debug.so',
  'libns3-dev-dsdv-debug.so',
  'libns3-dev-dsr-debug.so',
  'libns3-dev-energy-debug.so',
  'libns3-dev-fd-net-device-debug.so',
  'libns3-dev-flow-monitor-debug.so',
  'libns3-dev-internet-apps-debug.so',
  'libns3-dev-internet-debug.so',
  'libns3-dev-lr-wpan-debug.so',
  'libns3-dev-lte-debug.so',
  'libns3-dev-mesh-debug.so',
  'libns3-dev-mobility-debug.so',
  'libns3-dev-mpi-debug.so',
  'libns3-dev-netanim-debug.so',
  'libns3-dev-network-debug.so',
  'libns3-dev-nix-vector-routing-debug.so',
  'libns3-dev-olsr-debug.so',
  'libns3-dev-point-to-point-debug.so',
  'libns3-dev-point-to-point-layout-debug.so',
  'libns3-dev-propagation-debug.so',
  'libns3-dev-sixlowpan-debug.so',
  'libns3-dev-spectrum-debug.so',
  'libns3-dev-stats-debug.so',
  'libns3-dev-tap-bridge-debug.so',
  'libns3-dev-test-debug.so',
  'libns3-dev-topology-read-debug.so',
  'libns3-dev-traffic-control-debug.so',
  'libns3-dev-uan-debug.so',
  'libns3-dev-virtual-net-device-debug.so',
  'libns3-dev-wave-debug.so',
  'libns3-dev-wifi-debug.so',
  'libns3-dev-wimax-debug.so',
  'libns3-dev-openflow-debug.so'
];

const include = [ 
  'ns3-dev/ns3/core-module.h',
  'ns3-dev/ns3/network-module.h',
  'ns3-dev/ns3/internet-module.h',
  'ns3-dev/ns3/point-to-point-module.h',
  'ns3-dev/ns3/applications-module.h',
  'ns3-dev/ns3/internet-apps-module.h',
  'ns3-dev/ns3/csma-module.h',
  'ns3-dev/ns3/netanim-module.h',
  'ns3-dev/ns3/openflow-module.h',
  'ns3-dev/ns3/traffic-control-helper.h',
  'ns3-dev/ns3/traffic-control-layer.h',
  'ns3-dev/ns3/trace-helper.h',
  'ns3-dev/ns3/wifi-module.h',
  'ns3-dev/ns3/ipv4-routing-helper.h',
  'openflow/openflow.h'
];

module.exports = {
  systemsSupported,
  sharedObjects,
  include,
};
